### ISSUE TITLE
Individual Project Checkpoint 1 Ready for Review

### ISSUE THREAD

**Issue by spartan7777** [spartan7777/ConceptCompendium#2]
@pawaitemadisoncollege
My Individual Project Checkpoint 1 is ready for review.
I have added in all of the additional user stories as discussed. Please let me know if I added them all as intended. I also added some time allotments to my Project Plan to help me maintain forward progress on everything I am trying to do. Hopefully these are more towards your guidance on putting some time to each of these project plan steps.

**Comment by pawaitemadisoncollege** [comment]
That was quick turnaround @spartan7777!  A couple things:

1. Signing up for an account and logging in should be separated into two user stories. https://github.com/spartan7777/ConceptCompendium/blob/a36cfe27fcbe41c7914ea2c802fb62b8b69ea721/ConceptCompendium-Checkpoint%201/EnterpriseJava_Spring2021_Ogedengbe_ConceptCompendium_CheckPoint-1.txt#L49-L51
2. The project plan should reflect the specific user stories and target dates as to when you will work on each user story. These dates can and likely will, change, but I want you to lay them out with some details so we both have a good idea of what your tasks are during a given week.  This may provide some inspiration:  https://github.com/mad-java-ent-s21/FatBikeTrailReports/blob/main/ProjectPlan.md
