### ISSUE TITLE
Updated Checkpoint  Ready For Review

### ISSUE THREAD

**Issue by spartan7777** [spartan7777/ConceptCompendium#3]
@pawaitemadisoncollege
My Individual Project Checkpoint 1 has been updated and is ready for another review.
I have added in all of the additional user stories as discussed. I also looked at the trail reports for inspiration on how to provide a check list of tasks for this project with target dates for each week. I listed everything I can think of at this time that will go into making this project work, and I tried to lay out enough time to do all of these things along with time to review and refine things as needed. If I need to do more for these tasks, or go about creating the tasks on this list in a different way, let me know.

**Comment by pawaitemadisoncollege** [comment]
This looks better @spartan7777. Checkpoint 1 is complete.

As I mentioned last week, I highly recommend an iterative approach to getting the round trip from DB to JSP working, but ultimately it is up to you how you organize your work.  

Remember to include tasks for deploying to AWS (due as part of checkpoint 3). I recommend regular deploys to ensure things continue working both locally and on "production"
