### ISSUE TITLE
Code Review 1

### ISSUE THREAD

**Issue by snstclair** [spartan7777/ConceptCompendium#6]
# Design/Code Review 1

### Reviewer: Sydney St. Clair

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.| 4 Your statement is very well thought out and articulated! |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. | 4 Your design document was nicely layed out, minus the missing buttons. I like that you don't want too many back buttons on your application, but I could see that being pretty annoying for a user, if they need to say compare two creatures to make sure they're not too similar, having to search again could turn some people away.  |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>| 3  |
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage.  | 5 Your code all looked good other than needed a truly genericDao that takes an entity. There is a great video in the follow up videos for week 5.

**Comment by pawaitemadisoncollege** [comment]
A couple more things:

Opportunity for using templating in the jsps, for example the head tag is nearly identical across pages.  https://github.com/spartan7777/ConceptCompendium/blob/19581d0722b3995622c584aaf8f8526ef6b02619/src/main/webapp/WEB-INF/JSPs/searchresults.jsp#L3-L8

Some sneaky printlns and stack traces:
![Screen Shot 2021-02-26 at 2 18 36 PM](https://user-images.githubusercontent.com/13874466/109350845-d5c92700-783d-11eb-86f9-17efe0715ab1.png)
