### ISSUE TITLE
Code Review 1

### ISSUE THREAD

**Issue by RobIsInSchool** [spartan7777/ConceptCompendium#7]
# Design/Code Review 1

​

## Project:

Concept Compendium

### Developer:

​Tosan Ogedengbe

### Reviewer:

​Robert Adams

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.| Project's purpose is crystal clear. Professionally presented. Very clear explanation of problem and solution. It already sounds like an app I might use! |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. | The flow of the design looked great. However, showing the buttons/navigation on the design images would help with this, as they are currently missing, but the navigation can be easily inferred. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>| Model looks to be at a good spot. There are at least two one-to-many relationships that I remember. However, the scope of this project will potentially need quite a few more tables than are currently present |
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage. | Maven structure is present, as is a .gitignore (although, it appears to be the default. It's really useful to hide things from the public, like sensitive database information for instance). There is some recurring segments in the JSPs, but that should be an easy fix. Existing classes are of good size. Logging is used. Unit tests are good for this point in time | 

  

​

​

​

**Comment by RobIsInSchool** [comment]
I can't figure out how to get the table to format properly, so I apologize for that.

**Comment by pawaitemadisoncollege** [comment]
I think (part of) the problem are the blank lines between each table "row".  

This should render correctly, for example:
`|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have at least one "kudos" and one suggestion for improvement|`

**Comment by RobIsInSchool** [comment]
@pawaitemadisoncollege That did the trick! Thanks.

**Comment by pawaitemadisoncollege** [comment]
@RobIsInSchool and @spartan7777 One thing to add to this, there are some sneaky System.out.printlns and stack traces out there (screenshots below may not be all-inclusive).  Don't you love it when instructor-provided code has built-in standards "violations"?  Be sure to replace those with logging statement prior to Checkpoint 2.

![Screen Shot 2021-02-26 at 1 36 24 PM](https://user-images.githubusercontent.com/13874466/109346794-d068de00-7837-11eb-9680-219b8704a454.png)
![Screen Shot 2021-02-26 at 1 36 36 PM](https://user-images.githubusercontent.com/13874466/109346800-d1017480-7837-11eb-9070-ac5ad29a4aa7.png)
